### ISSUE TITLE
405 method not allowed

### ISSUE THREAD

**Issue by ensemblebd** [SymbolSource/SymbolSource#5]
1. Cloned repo
2. Restored packages
3. Built system
4. Published system to IIS server (with app pool perms on whole dir and packages target dir)
5. Followed setup guide (for appSettings)

```
  <appSettings>
	<add key="Container.SecurityType" value="SymbolSource.Contract.Security.NullSecurityService, SymbolSource.Contract" />
	<add key="InstanceSalt" value="mysalt" />
	<add key="NullSecurity.PushApiKeys" value="123456-apikey-here" />
	<add key="NullSecurity.AllowNamedFeeds" value="false" />
	
	<add key="Container.StorageType" value="SymbolSource.Contract.Storage.LocalStorageService, SymbolSource.Contract" />
	<add key="LocalStorage.RootPath" value="C:\inetpub\wwwroot\parent_folder\ihavewriteprivshere" />
	
	<add key="Container.SchedulerType" value="SymbolSource.Contract.Scheduler.FileSchedulerService, SymbolSource.Contract" />
	
	
  </appSettings>
```

And yet: 
`nuget push mysymbolpack.symbols.nupkg "123456-apikey-here" -source https://myinternaloffice.subnet`
Response is as follows:
```
  PUT https://myinternaloffice.subnet/api/v2/package/
  MethodNotAllowed https://myinternaloffice.subnet/api/v2/package/ 133ms
Response status code does not indicate success: 405 (Method Not Allowed).
```
The root domain boots up fine with an xml output.
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom" xml:base="https://myinternaloffice.subnet/">
<workspace>
<atom:title type="text">Default</atom:title>
<collection href="Packages">
<atom:title type="text">Packages</atom:title>
</collection>
</workspace>
</service>
```

What have I done incorrectly?

**Comment by ensemblebd** [comment]
I solved this by adding to web.config. 
```
		<!--Add the following to the beginning of <system.webServer><modules>:-->
		<remove name="WebDAVModule" />
		<!--Add the following to the beginning of <system.webServer><handlers>:-->
		<remove name="WebDAV" />
```
As per https://stackoverflow.com/questions/16451183/405-method-not-allowed-in-nuget-push

Now it's stating 500 internal server error. 
And so I dig on...

**Comment by ensemblebd** [comment]
Problem was more missing appsettings...
```
	<add key="Support.InsightsWebAppInstrumentationKey" value="" />
	<add key="Support.InsightsWebJobInstrumentationKey" value="" />
	<add key="Support.IntercomAppId" value="" />
	<add key="Support.IntercomApiKey" value="" />
```
Now for the real error, the Key for local storage is incorrect, and yet the error is totally unhandled. 

`	<add key="LocalStorage.RootPath" value="thepath" />`
should be (**aka incorrect Readme documentation**)
`	<add key="FileStorage.RootPath" value="thepath" />`

And now everything works perfectly. 

Highly recommend that you add these major points to the readme, such a simple change, such a massive difference.

**Comment by TripleEmcoder** [comment]
Thank you for all the time you spent on investigating this issue, and providing the solution. Funny enough I stumbled upon the 405 Method Not Allowed issue just last week in a different project, but did not think of SymbolSource, that it might also be affected. Apparently Azure Websites, where the service is primarily hosted, does not have WebDAV installed, and does not exhibit this issue. By the way this is a problem for any REST-ful services: https://stackoverflow.com/questions/6147181/405-method-not-allowed-in-iis7-5-for-put-method

As for `FileStorage.RootPath` you are also absolutely right. In `Web.config` the name of the setting was correct, but the README needed an update. This is all because `LocalStorageService` was once called `FileStorageService` and the name of the setting was left behind for backward compatability.

**Comment by ensemblebd** [comment]
Awesome thank you!!!

And want to say it has been working excellently, and am very appreciative for your work on this project. Thank you!
